---
name: code-quality
on:
  push:
    branches:
      - master
  pull_request:

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.11.0'

      - name: Install dependencies
        run: npm ci
      - name: Run linters
        run: npm run lint:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.11.0'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --coverage --ci --runInBand

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.11.0'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
