name: Sync `docs` directory to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Run GitHub Action to sync docs in `docs` directory
      - name: Readme.io GitHub Action
        uses: readmeio/rdme@7.2.0
        with:
          rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=1.0
